name: Source data
on:
  workflow_dispatch:
  schedule:
    - cron: '* 3 * * *'
jobs:
  update_dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download data file
        uses: carlosperate/download-file-action@v1.0.3
        id: download
        with:
          file-url: 'http://www.fa-technik.adfc.de/code/opengeodb/DE.tab'
          location: 'data/tmp'
      - name: Print file path
        run: echo "Find the data at ${{ steps.download.outputs.file-path }}"
      - name: Compute hash
        id: hashsum
        working-directory: 'data/tmp'
        run: |
          HASH="$(sha256sum DE.tab)"
          echo "$HASH"
          echo "::set-output name=hash::${HASH}"
      - name: Compare hashes
        working-directory: 'data'
        run: |
          if [[ -f "DE.tab" ]] \
            && sha256sum --check --status ${{ steps.hashsum.outputs.hash }}; then
            echo "Should be the same file!"
          else
            echo "Move updated file to repo location."
          fi
