name: Source data
on:
  schedule:
    - cron: '* 3 * * *'
jobs:
  get_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compute hash
        id: hashsum
        run: |
          echo ::set-output name=hash::${{ hashFiles('data/DE.tab') }}
      - name: Print hash
        run: echo "${ steps.hashsum.outputs.hash }"

