name: Source data
on:
  workflow_dispatch:
  schedule:
    - cron: '* 3 * * *'
jobs:
  get_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compute hash
        id: hashsum
        run: echo "::set-output name=HASH::$(sha256sum data/DE.tab)"
      - name: Print hash
        run: echo "${{ steps.hashsum.HASH }}"


