name: Source data
on:
  workflow_dispatch:
  schedule:
    - cron: '* 3 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      need-update: ${{ steps.update_check.outputs.UPDATE_FLAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #- name: Download data file
        #id: download
        #uses: carlosperate/download-file-action@v1.0.3
        #with:
          #file-url: 'http://www.fa-technik.adfc.de/code/opengeodb/DE.tab'
          #location: 'data/tmp'
      - name: Check for update
        id: update_check
        #working-directory: 'data/tmp'
        working-directory: 'data'
        run: |
            #sha256sum --check --status ../DE.tab.sha256 \
            sha256sum --check DE.tab.sha256 \
              || echo "::set-output name=UPDATE_FLAG::{{ true }}"
      #- name: Upload data file (artifact)
        #if: ${{ steps.update_check.outputs.UPDATE_FLAG }}
        #uses: actions/upload-artifact@v2
        #with:
          #name: plz-data
          #path: "${{ steps.download.outputs.file-path }}"
          #retention-days: 1
  build:
    needs: update
    runs-on: ubuntu-latest
    if: ${{ needs.update.outputs.need-update }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #- name: Download data file (artifact)
        #uses: actions/download-artifact@v2
        #id: download_artifact
        #with:
          #name: plz-data
          #path: 'data/tmp'
      - name: Start build
        working-directory: 'data'
        run: |
            echo "Beginning of build job..."
            ls -R 
      #- name: Generate checksum
        #if: ${{ success() }}
        #working-directory: 'data'
        #run: |
          #sha256sum tmp/plz-data > DE.tab.sha256
      #- name: Push changes
        #run: |
          #git config --global user.name "github-actions[bot]"
          #git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          #git add data/DE.tab.sha256 german-plz/0.2.0/package.yml
          #git commit -m 'Autogenerate package.yml and add checksum for source data'
          #git push
        #with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
